### ISSUE TITLE
Команда start создает новую запись в текущий день

### ISSUE THREAD

**Issue by ghost** [Vehsamrak/worktime#1]
Сделать так, чтобы команда start проверяла запись текущего дня и если он есть, то не создавала новую

**Comment by Vehsamrak** [comment]
#08b8a60c8f572a7f959c4ce8c21f299680f8be6e

**Comment by vehsamrak** [comment]
@igor-lazarev-iqoption 
https://github.com/Vehsamrak/worktime/releases/tag/1.2.0
По ссылке - бинарник с новой версией
